#!/usr/bin/with-contenv bash

# create directory structure
mkdir -p \
	/config/www/{uploads,files,images}

# Echo init finish for test runs
if [ -n "${TEST_RUN}" ]; then
	echo '[services.d] done.'
fi

# set permissions
chown -R abc:abc \
	/config \
	/var/www/
